language: c
script:
    - ./bootstrap
    - ./configure
    - make
    - make check
before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y unifdef
    - wget https://cmocka.org/files/1.1/cmocka-1.1.1.tar.xz
    - tar -xJvf cmocka-1.1.1.tar.xz
    - pushd cmocka-1.1.1 && ./configure --prefix=/usr && make && sudo make install && popd
